version: "3.7"
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  boot:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    links:
      - redis